---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on debian nodes
    apt:
      name: "{{myjavapackonubuntu}}"
      state: present 
    when: ansible_os_family=="Debian"

  - name: install java on amazon nodes
    dnf:
      name: "{{myjavapackonRedHat}}"
      state: present
    when: ansible_os_family=="RedHat"

