---
- hosts: 172.31.5.252 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserer
    apt:
      name: apache2
      state: present 

  - name: i want to create folder
    file:  
      path: /home/maha/myfolder
      state: directory
    
  - name: i want to copy a file into myfolder 
    copy: 
      src: mytestfile
      dest: /home/maha/myfolder

  - name: i want to copyy index.j2 page into nodes side
    template: 
       src:  myindex.j2
       dest: /var/www/html/index.html

  - name: i want to download internet file 
    get_url:
      url: http://example.com/path/file.conf
      dest: /etc/foo.conf
      force_basic_auth: yes

       
       

    
