---
- hosts: 172.31.5.252 
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserer
    apt:
      name: apache2
      state: present 

  - name: i want to create folder
    file:  
      path: /home/maha/myfolder
      state: directory
    
  - name: i want to copy a file into myfolder 
    copy: 
      src: mytestfile
      dest: /home/maha/myfolder

    
