---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install apache2 websever ( sudo apt-get install apache2 )
    apt:
      name: apache2
      state: present
  
  - name: i want to start apache2 webserver ( sudo service apache2 start)
    serivce: 
        name: apache2
        state: started
  
      